name: Copycat
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /
        dst_path: /source/XiaozhiSans/
        dst_owner: XiaozhiSans
        dst_repo_name: blog
        dst_branch: main
        src_branch: main
        clean: false
        commit_message: 'Merge XiaozhiSans:main into blog:main'
        username: Xia0zhiSans
        email: 171530684+Xia0zhiSans@users.noreply.github.com
